"""E2E tests for app embed secret CRUD."""

import pytest


def _create_app(client, headers, slug):
    r = client.post("/api/applications", headers=headers, json={"name": slug, "slug": slug, "app_model": "inline_v1"})
    assert r.status_code == 201, r.text
    return r.json()


def _delete_app(client, headers, app_id):
    r = client.delete(f"/api/applications/{app_id}", headers=headers)
    assert r.status_code in (200, 204), r.text


@pytest.mark.e2e
class TestAppEmbedSecrets:
    @pytest.fixture
    def test_app(self, e2e_client, platform_admin):
        app = _create_app(e2e_client, platform_admin.headers, "embed-secret-test")
        yield app
        _delete_app(e2e_client, platform_admin.headers, app["id"])

    def test_create_embed_secret_autogenerated(self, e2e_client, platform_admin, test_app):
        """Creating a secret without providing one should auto-generate it."""
        r = e2e_client.post(
            f"/api/applications/{test_app['id']}/embed-secrets",
            headers=platform_admin.headers,
            json={"name": "Test Secret"},
        )
        assert r.status_code == 201, r.text
        data = r.json()
        assert "raw_secret" in data
        assert len(data["raw_secret"]) > 20
        assert data["name"] == "Test Secret"
        assert data["is_active"] is True

    def test_create_embed_secret_user_provided(self, e2e_client, platform_admin, test_app):
        """Creating a secret with a user-provided value should store and return it."""
        provided = "my-halo-secret-abc123"
        r = e2e_client.post(
            f"/api/applications/{test_app['id']}/embed-secrets",
            headers=platform_admin.headers,
            json={"name": "Halo Prod", "secret": provided},
        )
        assert r.status_code == 201, r.text
        assert r.json()["raw_secret"] == provided

    def test_list_embed_secrets_hides_raw(self, e2e_client, platform_admin, test_app):
        """Listing secrets should NOT return the raw secret value."""
        e2e_client.post(
            f"/api/applications/{test_app['id']}/embed-secrets",
            headers=platform_admin.headers,
            json={"name": "Listed Secret"},
        )
        r = e2e_client.get(
            f"/api/applications/{test_app['id']}/embed-secrets",
            headers=platform_admin.headers,
        )
        assert r.status_code == 200, r.text
        secrets = r.json()
        assert len(secrets) >= 1
        for s in secrets:
            assert "raw_secret" not in s
            assert "secret_encrypted" not in s

    def test_deactivate_embed_secret(self, e2e_client, platform_admin, test_app):
        """Should be able to deactivate an embed secret."""
        create_r = e2e_client.post(
            f"/api/applications/{test_app['id']}/embed-secrets",
            headers=platform_admin.headers,
            json={"name": "To Deactivate"},
        )
        secret_id = create_r.json()["id"]
        r = e2e_client.patch(
            f"/api/applications/{test_app['id']}/embed-secrets/{secret_id}",
            headers=platform_admin.headers,
            json={"is_active": False},
        )
        assert r.status_code == 200, r.text
        assert r.json()["is_active"] is False

    def test_delete_embed_secret(self, e2e_client, platform_admin, test_app):
        """Should be able to delete an embed secret."""
        create_r = e2e_client.post(
            f"/api/applications/{test_app['id']}/embed-secrets",
            headers=platform_admin.headers,
            json={"name": "To Delete"},
        )
        secret_id = create_r.json()["id"]
        r = e2e_client.delete(
            f"/api/applications/{test_app['id']}/embed-secrets/{secret_id}",
            headers=platform_admin.headers,
        )
        assert r.status_code == 204, r.text

    def test_non_admin_cannot_manage_secrets(self, e2e_client, org1_user, test_app):
        """Regular org users should NOT be able to manage embed secrets."""
        r = e2e_client.post(
            f"/api/applications/{test_app['id']}/embed-secrets",
            headers=org1_user.headers,
            json={"name": "Unauthorized"},
        )
        assert r.status_code == 403, r.text
